baseURL = 'https://ghaniafza.github.io/test-site/'
languageCode = 'en-us'
title = 'Test Site'
theme = "shibui"

[params]
  author = "Nia"
  email = "your.email@example.com"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
